# Generated by Django 4.1.3 on 2023-06-21 16:11

from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import experimentos.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fecha_final', models.DateTimeField()),
                ('frecuencia', models.FloatField()),
                ('cantidad_imagenes', models.IntegerField(editable=False, null=True)),
                ('imagenes_capturadas', models.IntegerField(default=0, editable=False)),
                ('observaciones', models.TextField(max_length=200)),
                ('status', models.CharField(default='Creado', editable=False, max_length=20)),
                ('progreso', models.FloatField(default=0, editable=False)),
                ('status_2', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Activo', 'Activo'), ('Creado', 'Creado'), ('Finalizado', 'Finalizado')], default=experimentos.enums.SetupStatus['activo'], enum_class=experimentos.enums.SetupStatus, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_interval', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('10 secs', '10 secs'), ('15 mins', '15 mins'), ('30 mins', '30 mins'), ('1 hour', '1 hour'), ('2 hour', '2 hour'), ('3 hour', '3 hour')], default=experimentos.enums.TimeInterval['thirty_mins'], enum_class=experimentos.enums.TimeInterval, max_length=7)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Experimento',
                'verbose_name_plural': 'Experimentos',
            },
        ),
        migrations.CreateModel(
            name='Semillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('germinadas', models.IntegerField()),
                ('no_germinadas', models.IntegerField()),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentos.experimento')),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.ImageField(upload_to='masks')),
                ('fecha', models.DateTimeField()),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentos.experimento')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pics')),
                ('fecha', models.DateTimeField()),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentos.experimento')),
            ],
        ),
    ]
