# Generated by Django 4.1.3 on 2023-06-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experimentos", "0002_alter_experimento_status_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimento",
            name="status",
            field=models.CharField(default="Iniciado", editable=False, max_length=20),
        ),
    ]
