# Generated by Django 4.1.3 on 2023-06-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experimentos", "0005_alter_experimento_status_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetriDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
