# Generated by Django 4.1.2 on 2022-11-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0006_alter_experimento_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='cantidad_imagenes',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
