# Generated by Django 4.1.3 on 2023-06-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('experimentos', '0007_alter_petridish_options_experimento_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
    ]
