# Generated by Django 4.1.3 on 2022-11-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0007_alter_experimento_cantidad_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='frecuencia',
            field=models.FloatField(),
        ),
    ]
