# Generated by Django 4.1.3 on 2022-11-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0008_alter_experimento_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='progreso',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
