# Generated by Django 4.1.3 on 2022-11-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0009_experimento_progreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mask',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
