# Generated by Django 4.1.3 on 2023-03-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0010_alter_image_fecha_alter_mask_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semillas',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
