# Generated by Django 4.1.3 on 2023-03-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0011_alter_semillas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='imagenes_capturadas',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
